### ISSUE TITLE
CDD_Concrete 2018 FBS error

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/HIO#15]
Here is the log where error occurs when running the 2018 file
```
2023-12-04 19:28:08 INFO     Save the comparison of FlowByActivity load to FlowBySector total FlowAmounts for material_processing in validation log file
2023-12-04 19:28:08 INFO     Completed flowbysector for material_processing
Traceback (most recent call last):
  File "C:\\\HIO\flowsa\run_CDD_concrete_national_2018.py", line 16, in <module>
    flowsa.flowbysector.main(method=method, fbsconfigpath=fbsMethodPath,
  File "C:\\\HIO\venv\Lib\site-packages\flowsa\flowbysector.py", line 159, in main
    flows = load_source_dataframe(method, k, v, download_FBA_if_missing,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\\\HIO\venv\Lib\site-packages\flowsa\flowbysector.py", line 90, in load_source_dataframe
    if source_dict['data_format'] == 'FBA':
       ~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'int' object is not subscriptable

```

And in contrast the log with the successful 2014 run ..
```
2023-12-04 19:16:58 INFO     Completed flowbysector for material_processing
2023-12-04 19:16:58 INFO     Concat data for all activities
2023-12-04 19:16:58 INFO     Clean final dataframe
```

**Comment by WesIngwersen** [comment]
fyi @catherinebirney

**Comment by bl-young** [comment]
the spacing was off in the FBS method so it wasn't reading the method correctly. cb9bb50 should resolve the issue

**Comment by WesIngwersen** [comment]
confirmed this fixes it, thanks!
